'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by CodeSmith.
'     Version: 3.2.7.955
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Windows.Forms
Imports Syncfusion.Windows.Forms.Tools

Namespace Mbark.UI

#Region "  Thread-Safe ProgressBarAdv.Value Getter and Setter"

	' ---
	' This is generated code; edits will be lost.
	
	Public Module SafeProgressBarAdvValueGetterAndSetter

	Private Sub SetProgressBarAdvValueImplementation(ByVal control As ProgressBarAdv, ByVal value As Integer)
		control.Value = value
	End Sub

	''' <summary>
    ''' Provides a thread-safe mechanism for setting the value of a ProgressBarAdv.ProgressBarAdv property.
    ''' </summary>
    ''' <param name="control">Object to have its Value set</param>
    ''' <param name="value">Value assigned to target object's Value property</param>
    ''' <remarks>Automatically generated from SafeInvokeWrappers.cst</remarks>
	Public Sub SafeSetProgressBarAdvValue(ByVal control As ProgressBarAdv, ByVal value As Integer)
		SafeInvoke2ArgSub(Of ProgressBarAdv, Integer)(control, AddressOf SetProgressBarAdvValueImplementation, control, value)
	End Sub
	
	Private Function GetProgressBarAdvValueImplementation(ByVal control As ProgressBarAdv) As Integer
		Return control.Value
	End Function
	
	
	''' <summary>
    ''' Provides a thread-safe mechanism for getting the value of a ProgressBarAdv.ProgressBarAdv property.
    ''' </summary>
    ''' <param name="control">Object from which to retrieve Value value</param>
    ''' <remarks>Automatically generated from SafeInvokeWrappers.cst</remarks>
	Public Function SafeGetProgressBarAdvValue(ByVal control As ProgressBarAdv) As Integer
		Return SafeInvoke1ArgFunction(Of Integer, ProgressBarAdv)(control,  AddressOf GetProgressBarAdvValueImplementation, control)
	End Function
	
	End Module
	

#End Region
	

#Region "  Thread-Safe GradientLabel.Text Getter and Setter"

	' ---
	' This is generated code; edits will be lost.
	
	Public Module SafeGradientLabelTextGetterAndSetter

	Private Sub SetGradientLabelTextImplementation(ByVal control As GradientLabel, ByVal value As String)
		control.Text = value
	End Sub

	''' <summary>
    ''' Provides a thread-safe mechanism for setting the value of a GradientLabel.GradientLabel property.
    ''' </summary>
    ''' <param name="control">Object to have its Text set</param>
    ''' <param name="value">Value assigned to target object's Text property</param>
    ''' <remarks>Automatically generated from SafeInvokeWrappers.cst</remarks>
        <CLSCompliant(False)> Public Sub SafeSetGradientLabelText(ByVal control As GradientLabel, ByVal value As String)
            SafeInvoke2ArgSub(Of GradientLabel, String)(control, AddressOf SetGradientLabelTextImplementation, control, value)
        End Sub
	
	Private Function GetGradientLabelTextImplementation(ByVal control As GradientLabel) As String
		Return control.Text
	End Function
	
	
	''' <summary>
    ''' Provides a thread-safe mechanism for getting the value of a GradientLabel.GradientLabel property.
    ''' </summary>
    ''' <param name="control">Object from which to retrieve Text value</param>
    ''' <remarks>Automatically generated from SafeInvokeWrappers.cst</remarks>
        <CLSCompliant(False)> Public Function SafeGetGradientLabelText(ByVal control As GradientLabel) As String
            Return SafeInvoke1ArgFunction(Of String, GradientLabel)(control, AddressOf GetGradientLabelTextImplementation, control)
        End Function
	
	End Module
	

#End Region
	

#Region "  Thread-Safe GradientLabel.Visible Getter and Setter"

	' ---
	' This is generated code; edits will be lost.
	
	Public Module SafeGradientLabelVisibleGetterAndSetter

	Private Sub SetGradientLabelVisibleImplementation(ByVal control As GradientLabel, ByVal value As Boolean)
		control.Visible = value
	End Sub

	''' <summary>
    ''' Provides a thread-safe mechanism for setting the value of a GradientLabel.GradientLabel property.
    ''' </summary>
    ''' <param name="control">Object to have its Visible set</param>
    ''' <param name="value">Value assigned to target object's Visible property</param>
    ''' <remarks>Automatically generated from SafeInvokeWrappers.cst</remarks>
        <CLSCompliant(False)> Public Sub SafeSetGradientLabelVisible(ByVal control As GradientLabel, ByVal value As Boolean)
            SafeInvoke2ArgSub(Of GradientLabel, Boolean)(control, AddressOf SetGradientLabelVisibleImplementation, control, value)
        End Sub
	
	Private Function GetGradientLabelVisibleImplementation(ByVal control As GradientLabel) As Boolean
		Return control.Visible
	End Function
	
	
	''' <summary>
    ''' Provides a thread-safe mechanism for getting the value of a GradientLabel.GradientLabel property.
    ''' </summary>
    ''' <param name="control">Object from which to retrieve Visible value</param>
    ''' <remarks>Automatically generated from SafeInvokeWrappers.cst</remarks>
        <CLSCompliant(False)> Public Function SafeGetGradientLabelVisible(ByVal control As GradientLabel) As Boolean
            Return SafeInvoke1ArgFunction(Of Boolean, GradientLabel)(control, AddressOf GetGradientLabelVisibleImplementation, control)
        End Function
	
	End Module
	

#End Region
	

#Region "  Thread-Safe PictureBox.Visible Getter and Setter"

	' ---
	' This is generated code; edits will be lost.
	
	Public Module SafePictureBoxVisibleGetterAndSetter

	Private Sub SetPictureBoxVisibleImplementation(ByVal control As PictureBox, ByVal value As Boolean)
		control.Visible = value
	End Sub

	''' <summary>
    ''' Provides a thread-safe mechanism for setting the value of a PictureBox.PictureBox property.
    ''' </summary>
    ''' <param name="control">Object to have its Visible set</param>
    ''' <param name="value">Value assigned to target object's Visible property</param>
    ''' <remarks>Automatically generated from SafeInvokeWrappers.cst</remarks>
	Public Sub SafeSetPictureBoxVisible(ByVal control As PictureBox, ByVal value As Boolean)
		SafeInvoke2ArgSub(Of PictureBox, Boolean)(control, AddressOf SetPictureBoxVisibleImplementation, control, value)
	End Sub
	
	Private Function GetPictureBoxVisibleImplementation(ByVal control As PictureBox) As Boolean
		Return control.Visible
	End Function
	
	
	''' <summary>
    ''' Provides a thread-safe mechanism for getting the value of a PictureBox.PictureBox property.
    ''' </summary>
    ''' <param name="control">Object from which to retrieve Visible value</param>
    ''' <remarks>Automatically generated from SafeInvokeWrappers.cst</remarks>
	Public Function SafeGetPictureBoxVisible(ByVal control As PictureBox) As Boolean
		Return SafeInvoke1ArgFunction(Of Boolean, PictureBox)(control,  AddressOf GetPictureBoxVisibleImplementation, control)
	End Function
	
	End Module
	

#End Region
	

#Region "  Thread-Safe ProgressBar.Value Getter and Setter"

	' ---
	' This is generated code; edits will be lost.
	
	Public Module SafeProgressBarValueGetterAndSetter

	Private Sub SetProgressBarValueImplementation(ByVal control As ProgressBar, ByVal value As Integer)
		control.Value = value
	End Sub

	''' <summary>
    ''' Provides a thread-safe mechanism for setting the value of a ProgressBar.ProgressBar property.
    ''' </summary>
    ''' <param name="control">Object to have its Value set</param>
    ''' <param name="value">Value assigned to target object's Value property</param>
    ''' <remarks>Automatically generated from SafeInvokeWrappers.cst</remarks>
	Public Sub SafeSetProgressBarValue(ByVal control As ProgressBar, ByVal value As Integer)
		SafeInvoke2ArgSub(Of ProgressBar, Integer)(control, AddressOf SetProgressBarValueImplementation, control, value)
	End Sub
	
	Private Function GetProgressBarValueImplementation(ByVal control As ProgressBar) As Integer
		Return control.Value
	End Function
	
	
	''' <summary>
    ''' Provides a thread-safe mechanism for getting the value of a ProgressBar.ProgressBar property.
    ''' </summary>
    ''' <param name="control">Object from which to retrieve Value value</param>
    ''' <remarks>Automatically generated from SafeInvokeWrappers.cst</remarks>
	Public Function SafeGetProgressBarValue(ByVal control As ProgressBar) As Integer
		Return SafeInvoke1ArgFunction(Of Integer, ProgressBar)(control,  AddressOf GetProgressBarValueImplementation, control)
	End Function
	
	End Module
	

#End Region
End Namespace
