<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Mbark.CountryMessages.Messages.HeardIslandMcDonaldIslands", MessageId:="Member", Justification:="Neither an acronym nor a spelling mistake")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Mbark.CountryMessages.Messages.HeardIslandMcDonaldIslands[System.Globalization.CultureInfo]", MessageId:="Member", Justification:="Neither an acronym nor a spelling mistake")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Mbark.CountryMessages.Messages.ElSalvador", MessageId:="Member", Justification:="Neither an acronym nor a spelling mistake")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope:="member", Target:="Mbark.CountryMessages.Messages.ElSalvador[System.Globalization.CultureInfo]", MessageId:="Member", Justification:="Neither an acronym nor a spelling mistake")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Mbark.CountryMessages", Justification:="Namespace encapsulates generated code.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1809:AvoidExcessiveLocals", Scope:="member", Target:="Mbark.Countries..cctor()")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Mbark.UI.GlobalUISettings.Defaults")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Mbark.UI.GlobalUISettings")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Mbark.InfrastructureMessages", Justification:="Namespace encapsulates generated code.")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope:="namespace", Target:="Mbark.Debugging")> 
